-- CREDITS TO RAR.EXE

local Library = loadstring(Game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))()
local Window = Library:NewWindow("Hatchback Tower")
-- tabs
local Tab1 = Window:NewSection("Main")
local Tab2 = Window:NewSection("Misc.")
local Tab3 = Window:NewSection("CREDITS TO RAR.")
-- script
Tab1:CreateButton("Teleport to end", function()
   game.Players.LocalPlayer.character.HumanoidRootPart.CFrame = CFrame.new()
end)
Tab1:CreateButton("Teleport to Spawn", function()
   game.Players.LocalPlayer.character.HumanoidRootPart.CFrame = CFrame.new()
end)
Tab1:CreateButton("Get Sword", function()
   game.Players.LocalPlayer.character.HumanoidRootPart.CFrame = CFrame.new(176.005402, -438.074982, -158.682281, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    wait(0.2)
    game.Players.LocalPlayer.character.HumanoidRootPart.CFrame = CFrame.new()
end)
Tab2:CreateButton("Nameless Admin", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/ltseverydayyou/Nameless-Admin/refs/heads/main/Source.lua"))()
end)
Tab2:CreateButton("Infinite Yield", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
